export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const FETCH_USER_BEGIN = "FETCH_USER_BEGIN";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_ERROR = "FETCH_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const CHANGE_PASSWORD_BEGIN = "CHANGE_PASSWORD_BEGIN";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";

export const FETCH_PRODUCTS_BEGIN = "FETCH_PRODUCTS_BEGIN";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";

export const CREATE_SESSION_BEGIN = "CREATE_SESSION_BEGIN";
export const CREATE_SESSION_SUCCESS = "CREATE_SESSION_SUCCESS";
export const CREATE_SESSION_ERROR = "CREATE_SESSION_ERROR";

export const SET_SUBSCRIPTION_BEGIN = "SET_SUBSCRIPTION_BEGIN";
export const SET_SUBSCRIPTION_SUCCESS = "SET_SUBSCRIPTION_SUCCESS";
export const SET_SUBSCRIPTION_ERROR = "SET_SUBSCRIPTION_ERROR";

export const TOGGLE_MODAL_SUCCESS = "TOGGLE_MODAL_SUCCESS";
export const TOGGLE_TAGMODAL_SUCCESS = "TOGGLE_TAGMODAL_SUCCESS";
export const TOGGLE_EDIT_TRADEMODAL_SUCCESS = "TOGGLE_EDIT_TRADEMODAL_SUCCESS";

export const FETCH_TRADES_BEGIN = "FETCH_TRADES_BEGIN";
export const FETCH_TRADES_SUCCESS = "FETCH_TRADES_SUCCESS";
export const FETCH_TRADES_ERROR = "FETCH_TRADES_ERROR";

export const CREATE_TRADE_BEGIN = "CREATE_TRADE_BEGIN";
export const CREATE_TRADE_ERROR = "CREATE_TRADE_ERROR";
export const CREATE_TRADE_SUCCESS = "CREATE_TRADE_SUCCESS";

export const UPDATE_TRADE_BEGIN = "UPDATE_TRADE_BEGIN";
export const UPDATE_TRADE_ERROR = "UPDATE_TRADE_ERROR";
export const UPDATE_TRADE_SUCCESS = "UPDATE_TRADE_SUCCESS";

export const DELETE_TRADE_BEGIN = "DELETE_TRADE_BEGIN";
export const DELETE_TRADE_SUCCESS = "DELETE_TRADE_SUCCESS";
export const DELETE_TRADE_ERROR = "DELETE_TRADE_ERROR";

export const FETCH_EXECUTIONS_BEGIN = "FETCH_EXECUTIONS_BEGIN";
export const FETCH_EXECUTIONS_SUCCESS = "FETCH_EXECUTIONS_SUCCESS";
export const FETCH_EXECUTIONS_ERROR = "FETCH_EXECUTIONS_ERROR";

export const DELETE_EXECUTION_BEGIN = "DELETE_EXECUTION_BEGIN";
export const DELETE_EXECUTION_SUCCESS = "DELETE_EXECUTION_SUCCESS";
export const DELETE_EXECUTION_ERROR = "DELETE_EXECUTION_ERROR";

export const SET_SELECTED_TRADES = "SET_SELECTED_TRADES";

export const FETCH_JOURNALS_BEGIN = "FETCH_JOURNALS_BEGIN";
export const FETCH_JOURNALS_SUCCESS = "FETCH_JOURNALS_SUCCESS";
export const FETCH_JOURNALS_ERROR = "FETCH_JOURNALS_ERROR";

export const EDIT_JOURNAL_BEGIN = "EDIT_JOURNAL_BEGIN";
export const EDIT_JOURNAL_SUCCESS = "EDIT_JOURNAL_SUCCESS";
export const EDIT_JOURNAL_ERROR = "EDIT_JOURNAL_ERROR";

export const CREATE_JOURNAL_BEGIN = "CREATE_JOURNAL_BEGIN";
export const CREATE_JOURNAL_SUCCESS = "CREATE_JOURNAL_SUCCESS";
export const CREATE_JOURNAL_ERROR = "CREATE_JOURNAL_ERROR";

export const FETCH_TAGS_BEGIN = "FETCH_TAGS_BEGIN";
export const FETCH_TAGS_SUCCESS = "FETCH_TAGS_SUCCESS";
export const FETCH_TAGS_ERROR = "FETCH_TAGS_ERROR";

export const CREATE_TAG_BEGIN = "CREATE_TAG_BEGIN";
export const CREATE_TAG_SUCCESS = "CREATE_TAG_SUCCESS";
export const CREATE_TAG_ERROR = "CREATE_TAG_ERROR";

export const SET_SELECTED_TAGS = "SET_SELECTED_TAGS";

export const DELETE_TAG_BEGIN = "DELETE_TAG_BEGIN";
export const DELETE_TAG_SUCCESS = "DELETE_TAG_SUCCESS";
export const DELETE_TAG_ERROR = "DELETE_TAG_ERROR";

export const FETCH_CHARTDATA_BEGIN = "FETCH_CHARTDATA_BEGIN";
export const FETCH_CHARTDATA_SUCCESS = "FETCH_CHARTDATA_SUCCESS";
export const FETCH_CHARTDATA_ERROR = "FETCHT_CHARTDATA_ERROR";

export const CLEAR_ALERT = "CLEAR_ALERT";
